### ISSUE TITLE
Why are students making a pull request?

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-testing-filters-readme#2]
From the text, this seems like a code along, but when I open my copy, all the code is already in there and all tests are passing. Perhaps this should be a README and students just have to click I'm Done, or maybe remove all the code from the tests so students have to enter it in as they go.

**Comment by aturkewi** [comment]
@PeterBell

**Comment by PeterBell** [comment]
Either seems reasonable. Any thoughts as to which you'd go for @aturkewi ?
